### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by dakota11** [badslug/meteor-foundation-icons-general#1]
I added the package and it installed fine but I can't get any icons to appear.   Just see nothing.
I've added the correct tag as specified in the readme.

Any ideas?

**Comment by badslug** [comment]
Sorry for the slow turn around. I've updated the example project for this package:

https://github.com/badslug/meteor-foundation-icons-general-example

Can you try that and see if you see the 'gear' icon in the example? If it is showing up there, compare how it use presenting an icon with how you are doing it. One common "gotcha" is not including the foundation icon set ("general" in this case) as a class in addition to the icon specific class. If you are still having trouble please let me know - ideally post a sample project recreating the error and I'll troubleshoot as soon as I can. Thanks!

**Comment by dakota11** [comment]
Ok, that works.  I must not have been including the general.  Thanks!
